const getBrand = (productName) => {
    const brandMappings = {
        "T-shirt": ["Nike", "Adidas", "Puma", "Under Armour"],
        "Jeans": ["Levi's", "Wrangler", "Lee", "Calvin Klein"],
        "Dress": ["H&M", "Zara", "Forever 21", "ASOS"],
        "Hoodie": ["Champion", "Nike", "Adidas", "Under Armour"],
        "Sweater": ["Gap", "Old Navy", "H&M", "Uniqlo"],
        "Jacket": ["The North Face", "Columbia", "Patagonia", "Canada Goose"],
        "Skirt": ["Zara", "Forever 21", "H&M", "ASOS"],
        "Sneakers": ["Nike", "Adidas", "Puma", "New Balance"],
        "Running Shoes": ["Nike", "Adidas", "Brooks", "Asics"],
        "Sandals": ["Birkenstock", "Teva", "Chaco", "Keen"],
        "Backpack": ["North Face", "JanSport", "Herschel", "Patagonia"],
        "Watch": ["Rolex", "Tag Heuer", "Seiko", "Casio"],
        "Headphones": ["Sony", "Bose", "Sennheiser", "JBL"],
        "Laptop": ["Apple", "Dell", "HP", "Lenovo"],
        "Smartphone": ["Apple", "Samsung", "Google", "OnePlus"],
        "Gaming Console": ["PlayStation", "Xbox", "Nintendo", "PC"],
        "Camera": ["Canon", "Nikon", "Sony", "Fujifilm"],
        "Sunglasses": ["Ray-Ban", "Oakley", "Gucci", "Prada"],
        "Guitar": ["Fender", "Gibson", "Epiphone", "Taylor"],
        "Fitness Tracker": ["Fitbit", "Garmin", "Apple", "Samsung"],
        "Desk Chair": ["Herman Miller", "Steelcase", "IKEA", "Secretlab"],
        "Coffee Maker": ["Keurig", "Nespresso", "Breville", "Mr. Coffee"],
        "Bluetooth Speaker": ["UE", "JBL", "Anker", "Bose"],
        "External Hard Drive": ["Seagate", "Western Digital", "Samsung", "Toshiba"],
        "Tablet": ["Apple", "Samsung", "Amazon", "Microsoft"],
        "E-reader": ["Amazon Kindle", "Kobo", "Barnes & Noble", "Sony"],
        "Printer": ["HP", "Canon", "Epson", "Brother"],
        "Robot Vacuum": ["iRobot Roomba", "Eufy", "Neato Robotics", "Ecovacs"],
        "Drone": ["DJI", "Parrot", "Autel Robotics", "Yuneec"],
        "Mountain Bike": ["Trek", "Specialized", "Giant", "Cannondale"],
        "Microwave": ["Panasonic", "Samsung", "GE", "LG"],
        "Blender": ["Vitamix", "Ninja", "KitchenAid", "Oster"],
        "Handbag": ["Coach", "Michael Kors", "Kate Spade", "Louis Vuitton"],
        "Hat": ["New Era", "Goorin Bros", "Stetson", "Patagonia"],
        "Keyboard": ["Logitech", "Razer", "Corsair", "SteelSeries"],
        "Mouse": ["Logitech", "Razer", "Corsair", "SteelSeries"],
        "Monitor": ["Dell", "Samsung", "LG", "Asus"],
        "Projector": ["Epson", "BenQ", "Optoma", "ViewSonic"],
        "Vacuum Cleaner": ["Dyson", "Shark", "Bissell", "Hoover"],
        "Toaster": ["Cuisinart", "Breville", "Hamilton Beach", "KitchenAid"],
        "Food Processor": ["Cuisinart", "Hamilton Beach", "Ninja", "KitchenAid"],
        "Electric Kettle": ["Breville", "Cuisinart", "Hamilton Beach", "OXO"],
        "Rice Cooker": ["Zojirushi", "Aroma", "Instant Pot", "Tiger"],
        "Steam Iron": ["Rowenta", "Black+Decker", "Hamilton Beach", "Sunbeam"],
        "Hair Dryer": ["Dyson", "BaByliss", "Remington", "Conair"],
        "Electric Shaver": ["Braun", "Philips Norelco", "Panasonic", "Remington"],
        "Steamer": ["Rowenta", "Conair", "Jiffy", "PurSteam"],
        "Juicer": ["Breville", "Omega", "Hamilton Beach", "NutriBullet"],
        "Waffle Maker": ["Cuisinart", "Hamilton Beach", "Presto", "Black+Decker"]
    };

    return brandMappings[productName] || [];
};

module.exports = getBrand