
const materialsByProduct = {
    "T-shirt": ["Cotton"],
    "Jeans": ["Denim"],
    "Sneakers": ["Canvas", "Leather"],
    "Backpack": ["Canvas", "Nylon", "Polyester"],
    "Watch": ["Leather", "Metal"],
    "Headphones": ["Plastic", "Metal"],
    "Laptop": ["Plastic", "Metal"],
    "Smartphone": ["Plastic", "Metal", "Glass"],
    "Gaming Console": ["Plastic", "Metal"],
    "Camera": ["Plastic", "Metal"],
    "Sunglasses": ["Plastic", "Metal"],
    "Dress": ["Cotton", "Polyester", "Silk"],
    "Running Shoes": ["Mesh", "Rubber"],
    "Hoodie": ["Cotton", "Polyester", "Fleece"],
    "Sweater": ["Wool", "Cotton", "Polyester"],
    "Guitar": ["Wood", "Metal"],
    "Fitness Tracker": ["Plastic", "Rubber"],
    "Desk Chair": ["Plastic", "Metal"],
    "Coffee Maker": ["Plastic", "Metal"],
    "Bluetooth Speaker": ["Plastic", "Metal"],
    "External Hard Drive": ["Plastic", "Metal"],
    "Tablet": ["Plastic", "Metal", "Glass"],
    "E-reader": ["Plastic", "Metal", "Glass"],
    "Printer": ["Plastic", "Metal"],
    "Robot Vacuum": ["Plastic", "Metal"],
    "Drone": ["Plastic", "Metal"],
    "Mountain Bike": ["Metal", "Carbon Fiber"],
    "Microwave": ["Plastic", "Metal"],
    "Blender": ["Plastic", "Glass", "Metal"],
    "Handbag": ["Leather", "Canvas", "Nylon"],
    "Jacket": ["Polyester", "Nylon", "Leather"],
    "Skirt": ["Cotton", "Polyester", "Silk"],
    "Hat": ["Cotton", "Polyester", "Wool"],
    "Sandals": ["Leather", "Rubber", "Synthetic"],
    "Keyboard": ["Plastic"],
    "Mouse": ["Plastic", "Metal"],
    "Monitor": ["Plastic", "Metal"],
    "Projector": ["Plastic", "Metal"],
    "Vacuum Cleaner": ["Plastic", "Metal"],
    "Toaster": ["Plastic", "Metal"],
    "Food Processor": ["Plastic", "Metal"],
    "Electric Kettle": ["Plastic", "Metal"],
    "Rice Cooker": ["Plastic", "Metal"],
    "Steam Iron": ["Plastic", "Metal"],
    "Hair Dryer": ["Plastic", "Metal"],
    "Electric Shaver": ["Plastic", "Metal"],
    "Steamer": ["Plastic", "Metal"],
    "Juicer": ["Plastic", "Metal", "Glass"],
    "Waffle Maker": ["Plastic", "Metal"]
};
module.exports = materialsByProduct