
const sizesByProduct = {
    "T-shirt": ["XS", "S", "M", "L", "XL", "XXL"],
    "Jeans": ["36", "38", "40", "42", "44", "46", "48", "50", "52", "54", "56", "58", "60"],
    "Sneakers": ["5", "6", "7", "8", "9", "10", "11", "12"],
    "Backpack": [], 
    "Watch": [], 
    "Headphones": [], 
    "Laptop": [], 
    "Smartphone": [], 
    "Gaming Console": [], 
    "Camera": [], 
    "Sunglasses": [], 
    "Dress": ["XS", "S", "M", "L", "XL", "XXL"],
    "Running Shoes": ["5", "6", "7", "8", "9", "10", "11", "12"],
    "Hoodie": ["XS", "S", "M", "L", "XL", "XXL"],
    "Sweater": ["XS", "S", "M", "L", "XL", "XXL"],
    "Guitar": [], 
    "Fitness Tracker": [], 
    "Desk Chair": [], 
    "Coffee Maker": [], 
    "Bluetooth Speaker": [], 
    "External Hard Drive": [], 
    "Tablet": [], 
    "E-reader": [], 
    "Printer": [], 
    "Robot Vacuum": [], 
    "Drone": [], 
    "Mountain Bike": [], 
    "Microwave": [], 
    "Blender": [], 
    "Handbag": [], 
    "Jacket": [], 
    "Skirt": [], 
    "Hat": [], 
    "Sandals": [], 
    "Keyboard": [], 
    "Mouse": [], 
    "Monitor": [], 
    "Projector": [], 
    "Vacuum Cleaner": [], 
    "Toaster": [], 
    "Food Processor": [], 
    "Electric Kettle": [], 
    "Rice Cooker": [], 
    "Steam Iron": [], 
    "Hair Dryer": [], 
    "Electric Shaver": [], 
    "Steamer": [], 
    "Juicer": [], 
    "Waffle Maker": []
};



module.exports = sizesByProduct