const nationalities = [
    "Argentinian",
    "Australian",
    "Belgian",
    "Brazilian",
    "Canadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Cuban",
    "Danish",
    "Egyptian",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Hungarian",
    "Indian",
    "Indonesian",
    "Iranian",
    "Irish",
    "Israeli",
    "Italian",
    "Japanese",
    "Kenyan",
    "Malaysian",
    "Mexican",
    "Moroccan",
    "Nigerian",
    "Norwegian",
    "Pakistani",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Russian",
    "Saudi Arabian",
    "South African",
    "South Korean",
    "Spanish",
    "Swedish",
    "Swiss",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Emirati",
    "British",
    "American",
    "Venezuelan",
    "Vietnamese",
    "Zimbabwean",
    "Dutch"
];
const getRandomNationality = () => {
    const randomIndex = Math.floor(Math.random() * nationalities.length);
    return nationalities[randomIndex];
};

module.exports=getRandomNationality
